### PR TITLE
Performance improvements

### PR DESCRIPTION
**Pull request by ProbablyComputingSquid**
# Performance improvement

- Improve performance,
- Improved efficiency. 
- Added comments
- deleted useless and redundant code
- overall fixes

dev plz accept

### CODE REVIEW

**Comment by hotcocoaNcode** [comment]
oh my god he actually did it, pyson has _okay_ code quality now. this is wild.

**Comment by ProbablyComputingSquid** [comment]
@OmegaGodzilla66  ACCEPT THIS

**Review by ProbablyComputingSquid — COMMENTED** [review]
This pull request is so good!
This is _not_ a biased review

**Review by nmd102 — APPROVED** [review]
This PR looks good to merge: I would highly recommend for this to be merged!

**Review by hotcocoaNcode — APPROVED** [review]
Wow, this PR sure does look even more merge-able now. Anybody would find the “accept changes” button hard to resist…

**Pull request merged**
