### PR TITLE
Fixed README.md

### PR DESCRIPTION
**Pull request by nmd102**
Fixed README formatting

### CODE REVIEW

**Comment by ProbablyComputingSquid** [comment]
so good committ

**Review by ProbablyComputingSquid — APPROVED** [review]
this PR looks so good, all these changes are ones that i've wanted

**Review by CoolSchnoodle — CHANGES_REQUESTED** [review]
There is still no line break between the 0.0.5 comment and the 0.0.4 label, please fix that. Other than that, the formatting is improved a lot, so good job.

**Review by CoolSchnoodle — APPROVED** [review]
Thank you for making the changes I asked for. Looks good to merge now!

**Pull request merged**
